# Generated by Django 2.0.8 on 2021-08-28 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('NewsApp', '0002_sportsnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 28, 20, 25, 33, 345730, tzinfo=utc)),
        ),
    ]
